grafana:
  # Need to set appropriate root URL for kibernetika proxy
  rootUrl: "root_url"
  persistence:
    enabled: true
    fromProvider: true
    #storageClass: anything
    accessMode: ReadWriteOnce
    size: 4Gi
    volume:
      hostPath:
        path: /path

prometheus:
  persistence:
    enabled: true
    fromProvider: true
    #storageClass: anything
    accessMode: ReadWriteOnce
    size: 10Gi
    volume:
      hostPath:
        path: /path
    pushVolume:
      hostPath:
        path: /path

nodeSelector:
  enabled: false
  labels:
    monitoring: monitoring

exportGPU: true
pushGateway:
  enabled: true
RBAC: true
