grafana:
  persistence:
    enabled: true
    storageClass: anything
    accessMode: ReadWriteOnce
    size: 1Gi

prometheus:
  persistence:
    enabled: true
    storageClass: anything
    accessMode: ReadWriteOnce
    size: 10Gi

exportGPU: true
pushGateway:
  enabled: true
RBAC: true
