---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
spec:
  backend:
    serviceName: grafana
    servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
    component: core
