kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
