---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-core
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
        component: core
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v1.4.1
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: prometheus-storage
          mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-core
      - name: prometheus-storage
        emptyDir: {}
        #hostPath:
          #path: /srv/prometheus
        #nfs:
          #server: 185.19.29.253
          #path: /export/prometheus
