---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: core
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      name: webui
      targetPort: 9090
  selector:
    app: prometheus
    component: core
