{{- if .Values.grafana.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
spec:
  {{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.grafana.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end -}}