{{- if .Values.RBAC }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: prometheus
  name: prometheus-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - nodes
  - endpoints
  verbs:
  - get
  - list
  - watch
{{- end }}
