{{- if .Values.prometheus.persistence.enabled -}}
{{- if .Values.prometheus.persistence.fromProvider -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-push
spec:
  {{- if .Values.prometheus.persistence.storageClass }}
  storageClassName: {{ .Values.prometheus.persistence.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.prometheus.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
{{- end -}}
{{- end -}}
