{{- if .Values.pushGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus-push
  labels:
    app: prometheus
    component: push
spec:
  ports:
    - port: 9091
      protocol: TCP
      name: api
  selector:
    app: prometheus
    component: push
{{- end }}

