{{- if .Values.pushGateway.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-push
  labels:
    app: prometheus
    component: push
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-push
      labels:
        app: prometheus
        component: push
    spec:
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
      {{- range $key, $value := .Values.nodeSelector.labels }}
        {{ $key }}: "{{ $value }}"
      {{- end }}
      {{- end }}
      containers:
      - name: prometheus
        image: prom/pushgateway:v0.6.0
        args:
          - '--persistence.file=/prometheus/data'
          - '--persistence.interval=5s'
        ports:
        - name: api
          containerPort: 9091
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: data
          mountPath: /prometheus
      volumes:
      - name: data
        {{- if .Values.prometheus.persistence.enabled }}
        {{- if .Values.prometheus.persistence.fromProvider }}
        persistentVolumeClaim:
          claimName: prometheus-push
        {{- else }}
{{ toYaml .Values.prometheus.persistence.pushVolume | indent 8 }}
        {{- end }}
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
