{{- if .Values.RBAC }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-kube-state-metrics
rules:
- apiGroups: [""]
  resources:
  - nodes
  - persistentvolumeclaims
  - pods
  - pods/status
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - namespaces
  verbs: ["list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["list", "watch"]
{{- end }}
